name: Send a Discord message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UCF4Wxdo3inmxP-Y59wXDsFw
    config:
      filter:
        title:
          $regex: "날씨"
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Prepare message
        id: prepare
        run: |
          TITLE="${{on.youtube.outputs.title}}"
          PUB_DATE="${{on.youtube.outputs.pubDate}}"
          KST_DATE=$(TZ="Asia/Seoul" date -d "$PUB_DATE" '+%Y년 %m월 %d일 %I:%M:%S %p')
          ESCAPED_TITLE=$(echo "$TITLE" | sed 's/\\/\\\\/g' | sed 's/"/＂/g' | sed "s/'/＇/g" | sed 's/\$/＄/g' | sed 's/`/＇/g' | sed 's/|/｜/g' | sed 's/\?/？/g' | sed 's/\*/＊/g' | sed 's/+/＋/g' | sed 's/(/（/g' | sed 's/)/）/g' | sed 's/{/｛/g' | sed 's/}/｝/g' | sed 's/\[/［/g' | sed 's/\]/］/g' | sed 's/;/；/g' | sed 's/&/＆/g' | sed 's/\^/＾/g' | sed 's/%/％/g' | sed 's/#/＃/g' | sed 's/@/＠/g' | sed 's/!/！/g' | sed 's/</＜/g' | sed 's/>/＞/g' | sed 's/~/～/g')
          echo "Escaped title: $ESCAPED_TITLE"
          echo "KST Date: $KST_DATE"
          echo "::set-output name=escaped_title::$ESCAPED_TITLE"
          echo "::set-output name=kst_date::$KST_DATE"
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_MBC }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_MBC }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`MBC 뉴스 - YouTube`'\n'**${{steps.prepare.outputs.escaped_title}}**'\n'${{on.youtube.outputs.link}}'\n\n'📅 ${{steps.prepare.outputs.kst_date}}"
