name: Send a Discord message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UCkinYTS9IHqOEwR1Sze2JTw
    config:
      filter:
        title:
          $regex: "[날씨]"
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Prepare message
        id: prepare
        run: |
          TITLE="${{on.youtube.outputs.title}}"
          echo "Original title: $TITLE"
          ESCAPED_TITLE=$(echo "$TITLE" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | sed "s/'/\\\'/g" | sed 's/\$/\\$/g' | sed 's/`/\\`/g' | sed 's/|/\\|/g' | sed 's/\?/\\?/g' | sed 's/\*/\\*/g' | sed 's/+/\\+/g' | sed 's/(/\\(/g' | sed 's/)/\\)/g' | sed 's/{/\\{/g' | sed 's/}/\\}/g' | sed 's/\[/\\[/g' | sed 's/\]/\\]/g' | sed 's/;/\\;/g' | sed 's/&/\\&/g' | sed 's/\^/\\^/g' | sed 's/%/\\%/g' | sed 's/#/\\#/g' | sed 's/@/\\@/g' | sed 's/!/\\!/g' | sed 's/</\\</g' | sed 's/>/\\>/g' | sed 's/~/\\~/g')
          echo "Escaped title: $ESCAPED_TITLE"
          echo "::set-output name=escaped_title::$ESCAPED_TITLE"
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_SBS }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_SBS }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`SBS 뉴스 - YouTube`'\n'**${{steps.prepare.outputs.escaped_title}}**'\n'${{on.youtube.outputs.link}}"
