name: Send a Discord message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UCnInluxu9QQdlWv2KdGlQ7g
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_WEATHERNEWS }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_WEATHERNEWS }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_WEATHERNEWS }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`웨더뉴스 - YouTube`'\n'**${{on.youtube.outputs.title}}**'\n'${{on.youtube.outputs.link}}"
