name: Send a Discord message when new Youtube videos update
on:
  youtube:
    channel_id:
      - UCCW7N13hV53wZ3ufTFtkmhA
jobs:
  discord:
    name: Send a message to discord
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_WEATHER }}
          DISCORD_USERNAME: ${{ secrets.DISCORD_USERNAME_WEATHER }}
          DISCORD_AVATAR: ${{ secrets.DISCORD_AVATAR_WEATHER }}
        uses: Ilshidur/action-discord@master
        with:
          args: "`옙TV - YouTube`'\n'**${{on.youtube.outputs.title}}**'\n'${{on.youtube.outputs.link}}"
